version: '3.4'
services:
  database:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
  testtask:
    image: testtask
    build:
      context: .
      dockerfile: .\DockerFile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - database